const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  getState: () => ipcRenderer.invoke('get-state'),
  setState: (state) => ipcRenderer.invoke('set-state', state),
  fetchInbox: (creds) => ipcRenderer.invoke('fetch-inbox', creds),
  openAppleMailReply: (payload) => ipcRenderer.invoke('open-apple-mail-reply', payload),
  fetchProxy: (payload) => ipcRenderer.invoke('fetch-proxy', payload),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  triggerGitUpdate: () => ipcRenderer.invoke('trigger-git-update'),
  onUpdateStatus: (cb) => ipcRenderer.on('update-status', (_, status) => cb(status)),
  stripeTestKey: () => ipcRenderer.invoke('stripe-test-key'),
  stripeCreateLinkSession: () => ipcRenderer.invoke('stripe-create-link-session'),
  stripeOpenLinkWindow: (payload) => ipcRenderer.invoke('stripe-open-link-window', payload),
  stripeGetAccounts: (payload) => ipcRenderer.invoke('stripe-get-accounts', payload),
  stripeSyncTransactions: (payload) => ipcRenderer.invoke('stripe-sync-transactions', payload),
  onStripeAuthComplete: (cb) => ipcRenderer.on('stripe-auth-complete', (_, data) => cb(data)),
  clientSaveFile:    (payload) => ipcRenderer.invoke('client-save-file', payload),
  clientReadFile:    (payload) => ipcRenderer.invoke('client-read-file', payload),
  clientDeleteFile:  (payload) => ipcRenderer.invoke('client-delete-file', payload),
  clientDeleteFolder:(payload) => ipcRenderer.invoke('client-delete-folder', payload),
  shootChooseFolder: ()        => ipcRenderer.invoke('shoot-choose-folder'),
  shootCheckExists:  (p)       => ipcRenderer.invoke('shoot-check-exists', p),
  shootCreateFolder: (payload) => ipcRenderer.invoke('shoot-create-folder', payload),
  shootOpenFolder:   (p)       => ipcRenderer.invoke('shoot-open-folder', p),
});
